### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by PetersOtto** [paskalito/hotfolder#4]
Hi Paskal

Your solution would be great to use but I can't get it to run. The folders are generated. The function is there with the right name but will not found.
Have you an Idee what I am doing wrong?

I am using Ubuntu 20.4.

Best regards
Otto

**mv: Aufruf von stat für 'processing/*' nicht möglich: Datei oder Verzeichnis nicht gefunden
The "in" Folder is Empty
The "in" Folder is Empty
The "in" Folder is Empty
The "in" Folder is Empty
The "in" Folder is Empty
The "in" Folder is Empty
Oh something is in the "in" Folder let us watch it more closely
1508
1508
mv: Aufruf von stat für 'in/*' nicht möglich: Datei oder Verzeichnis nicht gefunden
./hotfolder.sh: Zeile 69: ./functions/convert_pictures.sh: Datei oder Verzeichnis nicht gefunden
The "in" Folder is Empty
The "in" Folder is Empty**

**Comment by paskalito** [comment]
Hi :)

Happy to hear you`re interested in my hotfolder :)
Unfortunately i don't quiet see what could be wrong, and i deleted my Ubuntu 20.04 in favor of debian some time ago.
the only/best bet i have at the moment is: can you run the script from a path that does not contain any spaces? - or any other special characters in that regard..
(evendough that works anyway on my machine)

**Comment by paskalito** [comment]
I just +- coincidentally installed ubuntu 20.04 on my pi.
i got the same error and could fix it. - it appears quiet random to me but now the script is a bit more flexibel in a - very unneccesarry - way ^^
but it works now on the newest ubuntu so everything is fine :D

download the updated version and have fun :)

**Comment by PetersOtto** [comment]
Thank you for your support! It works perfect for me!
